### ISSUE TITLE
Unable to load the plugin at startup

### ISSUE THREAD

**Issue by NeglectDream** [bladejsy/VelocityAlreadyConnected#1]
[17:44:54 ERROR]: Couldn't pass ProxyInitializeEvent to velocityalreadyconnected 1.0-SNAPSHOT
java.lang.IllegalArgumentException: The plugin main instance is automatically registered.
        at com.velocitypowered.proxy.event.VelocityEventManager.register(VelocityEventManager.java:345) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at dev.hydro.velocityalreadyconnected.Main.onProxyInitialization(Main.java:32) ~[?:?]
        at dev.hydro.velocityalreadyconnected.Lmbda$21.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:840) [?:?]

**Comment by hydrojava** [comment]
Hey, what version of Velocity are you using?

**Comment by NeglectDream** [comment]
> Hey, what version of Velocity are you using?

3.3.0-#428

**Comment by hydrojava** [comment]
Hey, this has been fixed on the latest version now downloadable on Spigot.
